config/routes.rb
Rails.application.routes.draw do
  resources :steps
  resources :operations
  resources :crop_operations
  resources :livestock_operations
  resources :crop_inventories
  resources :livestock_inventories
  root to: 'counties#index'
  get '/counties/multiple', to: 'counties#show_multiple'
  resources :counties, only: [:index, :show] do
    resources :statistics, only: [:index]
  end
  resources :statistics, only: [:show]
  resources :energy_units, only: [:index]

  get '/crop_assumptions', to: 'application#crop_assumptions'
  get '/livestock_assumptions', to: 'application#livestock_assumptions'

  get '/links', to: 'application#links'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/statistic.rb
# Statisics (an instance of a NASS database statistic with some additional fields)
class Statistic < ApplicationRecord
  belongs_to :county

  scope :latest, -> { order(year_int: :desc) }

# NASS FIELDS
  scope :survey, -> { where(source_desc: 'SURVEY') }
  scope :census, -> { where(source_desc: 'CENSUS') }

  scope :total, -> { where(domain_desc: 'TOTAL') }

# CROP_INVENTORIES
  scope :acres, -> { where(unit_desc: 'ACRES') }
  scope :all_production_practices, -> { where(prodn_practice_desc: 'ALL PRODUCTION PRACTICES') }
  scope :harvested, -> { where(statisticcat_desc: 'AREA HARVESTED') }

# CROPS
  scope :field_crops, -> { where(group_desc: 'FIELD CROPS') }

  scope :corn_commodity, -> { where(commodity_desc: 'CORN') }
  scope :soybeans_commodity, -> { where(commodity_desc: 'SOYBEANS') }
  scope :oats_commodity, -> { where(commodity_desc: 'OATS') }
  scope :forage_commodity, -> { where(commodity_desc: 'HAY & HAYLAGE') }
  scope :hay_commodity, -> { where(commodity_desc: 'HAY') }
  scope :haylage_commodity, -> { where(commodity_desc: 'HAYLAGE') }


  scope :grain, -> { where(util_practice_desc: 'GRAIN') }
  scope :silage, -> { where(util_practice_desc: 'SILAGE') }


# LIVESTOCK_INVENTORIES

  scope :head, -> { where(unit_desc: 'HEAD') }
  scope :inventory, -> { where(statisticcat_desc: 'INVENTORY') } #as opposed to SALES
  scope :animals_and_products, -> { where(sector_desc: 'ANIMALS & PRODUCTS') } #as opposed to DEMOGRAPHICS
  scope :all_classes, -> { where(class_desc: 'ALL CLASSES') } #as opposed to BREEDING
  # also use :total above

# LIVESTOCK

  scope :cattle_commodity, -> { where(commodity_desc: 'CATTLE') }
    scope :beef_cows_class, -> { where(class_desc: 'COWS, BEEF') }
    scope :milk_cows_class, -> { where(class_desc: 'COWS, MILK') }
    scope :including_calves_class, -> { where(class_desc: 'INCL CALVES') }
    scope :excluding_cows_class, -> { where(class_desc: '(EXCL COWS)') }
  scope :goats_commodity, -> { where(class_desc: 'GOATS') }
  scope :hogs_commodity, -> { where(commodity_desc: 'HOGS') }

  scope :equine_commodity, -> { where(commodity_desc: 'EQUINE') }
  scope :horses_and_ponies_class, -> { where(class_desc: 'HORSES & PONIES') }
  scope :mules_burros_donkeys_class, -> { where(class_desc: 'MULES & BURROS & DONKEYS') }
  scope :sheep_class, -> { where(commodity_desc: 'SHEEP') }
    scope :ewes_class, -> { where(class_desc: 'EWES, BREEDING, GE 1 YEAR') }
    scope :including_lambs_class, -> { where(class_desc: 'INCL LAMBS') }
  scope :layers_class, -> { where(class_desc: 'LAYERS') }
  scope :broilers_class, -> { where(class_desc: 'BROILERS') }


# LAND AREA & USE
  scope :total_land_area, -> { where(commodity_desc: 'LAND AREA', statisticcat_desc: 'AREA', unit_desc: 'ACRES', domain_desc: 'TOTAL') }

  # specification of unit_desc and domain_desc may be redundant if query is County.first.statistics.total.cropland.acres
  # this is equivalent to County.first.statistics.cropland

  scope :cropland, -> { where(class_desc: 'CROPLAND', statisticcat_desc: 'AREA', unit_desc: 'ACRES', domain_desc: 'TOTAL') }
  scope :cropland_harvested, -> { where(class_desc: 'CROPLAND, HARVESTED', statisticcat_desc: 'AREA', unit_desc: 'ACRES', domain_desc: 'TOTAL') }
  scope :woodland, -> { where(class_desc: 'WOODLAND', statisticcat_desc: 'AREA', unit_desc: 'ACRES', domain_desc: 'TOTAL') }
  scope :pastureland, -> { where(class_desc: 'PASTURELAND', statisticcat_desc: 'AREA', unit_desc: 'ACRES', domain_desc: 'TOTAL') }
  scope :other_agland, -> { where(class_desc: '(EXCL CROPLAND & PASTURELAND & WOODLAND)', statisticcat_desc: 'AREA', unit_desc: 'ACRES', domain_desc: 'TOTAL') }
  # SUM these for total "ag land"

# TOTAL NUMBER OF FARM OPERATIONS
  scope :total_farm_operations, -> { where(domain_desc: 'TOTAL', statisticcat_desc: 'OPERATIONS', short_desc: 'FARM OPERATIONS - NUMBER OF OPERATIONS') }

# MISC
  scope :no_value, -> { where(value_float: 0 )}
  scope :with_value, -> { where.not(value_float: 0 )}


  #CHAINED SCOPES

  scope :corn_grain, -> { total.acres.corn_commodity.grain.harvested.all_production_practices.with_value.latest }
  scope :corn_silage, -> { total.acres.corn_commodity.silage.harvested.all_production_practices.with_value.latest }
  scope :soybeans, -> { total.acres.soybeans_commodity.harvested.all_production_practices.with_value.latest }
  scope :oats, -> { total.acres.oats_commodity.harvested.all_production_practices.with_value.latest }
  scope :forage, -> { total.acres.forage_commodity.harvested.all_production_practices.with_value.latest }


  scope :cattle, -> { total.head.cattle_commodity.with_value.latest }
  scope :beef_cows, -> { total.head.beef_cows_class.with_value.latest }
  scope :milk_cows, -> { total.head.milk_cows_class.with_value.latest }
  scope :other_cattle, -> { total.head.cattle_commodity.excluding_cows_class.with_value.latest }
  scope :broilers, -> { total.inventory.head.broilers_class.with_value.latest }
  scope :layers, -> { total.inventory.head.layers_class.with_value.latest }
  scope :hogs, -> { total.inventory.head.hogs_commodity.all_classes.with_value.latest }


  def suppressed?
    value.include? "(D)"
  end


  def self.fetch_all_nass_statistics_for_existing_counties
    County.find_each do |c|
      fetch_nass_statistics_for_county(c, {year__GE: 2012} )
    end
  end



  def self.fetch_nass_statistics_for_county(county, nass_query_options = {})
    # FIXME Your request will return a maximum of 50,000 data records. You can determine the returned record account before you execute the Quick Stats API call using the GET /api/get_counts function. If your request will return more than the maximum limit of 50,000 data records, you can do either of the following:


    q = { county_name: county.name.gsub("'", ' '), state_alpha: county.state_alpha } #apostrophes are converted to spaces Example: O'Brien (local) -> O Brien (NASS)

    q.merge!(nass_query_options)
      begin
        response = NassAPI.new.results({ query: q })
        if response.success?
          response.parsed_response['data'].each do |stat|
            Statistic.create_with(
              load_time: stat['load_time'], # load_time into the nass database
            ).find_or_create_by(
              short_desc: stat['short_desc'],
              value: stat['Value'],
              value_float: stat['Value'].delete(',').to_f, # convert NASS string without commas to float
              county_name: stat['county_name'],
              year: stat['year'], # convert to integer from NASS
              year_int: stat['year'].to_i ,#convert NASS string to integer
              county: county,
              util_practice_desc: stat['util_practice_desc'], # e.g.  'ALL UTILIZATION PRACTICES',
              prodn_practice_desc: stat['prodn_practice_desc'], # e.g.  'ALL PRODUCTION PRACTICES',
              domain_desc: stat['domain_desc'], # e.g.  'TOTAL',
              sector_desc: stat['sector_desc'], # e.g.  'ANIMALS & PRODUCTS', 'CROPS'
              reference_period_desc: stat['reference_period_desc'], # e.g.  'FIRST OF JAN',
              class_desc: stat['class_desc'], # e.g.  'COWS, MILK',
              agg_level_desc: stat['agg_level_desc'], # e.g.  'COUNTY',
              state_name: stat['state_name'], # e.g.  'IOWA',
              location_desc: stat['location_desc'], # e.g.  'IOWA, NORTHEAST, WINNESHIEK',
              state_alpha: stat['state_alpha'], # e.g.  'IA',
              asd_desc: stat['asd_desc'], # e.g.  'NORTHEAST',
              freq_desc: stat['freq_desc'], # e.g.  'POINT IN TIME',
              group_desc: stat['group_desc'], # e.g.  'LIVESTOCK', 'FIELD CROPS'
              unit_desc: stat['unit_desc'], # e.g.  'HEAD',
              source_desc: stat['source_desc'], # e.g.  'SURVEY',
              statisticcat_desc: stat['statisticcat_desc'], # e.g.  'INVENTORY', 'AREA PLANTED'
              commodity_desc: stat['commodity_desc'], # e.g.  'CATTLE', 'CORN'
              domaincat_desc: stat['domaincat_desc'],
            ) #unless stat['value'].delete(',').to_f == 0 # do not create suppressed statistics
          end
        else
          logger.debug "Something went wrong accessing NASS data for county: #{county.inspect} and the query: #{response}"
          return false
        end
      rescue HTTParty::Error
        # don´t do anything / whatever
        logger.debug "Something went wrong accessing NASS. The query response was as follows: #{(response)}"
      # rescue StandardError
        # rescue instances of StandardError,
        # i.e. Timeout::Error, SocketError etc
      end
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: %i[show edit update destroy]
  caches_page :show, :index

  # GET counties/96/statistics
  # GET counties/96/statistics.json
  def index
    @county = County.friendly.find(params[:county_id])
    @stats = @county.statistics
    @years = @stats.pluck('DISTINCT year_int').sort.reverse
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
    @county = @statistic.county
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit; end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url, notice: 'Statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_statistic
    @statistic = Statistic.includes(:county).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def statistic_params
    params.fetch(:statistic, {})
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.erb
<%= form_for(statistic) do |f| %>
<% if statistic.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(statistic.errors.count, "error") %>
      prohibited this statistic from being saved:</h2>

    <ul>
      <% statistic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Show', @statistic %>
|
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<div class='row'>
  <div class='col'>
    <div class="dashhead mt-4">
      <div class="dashhead-titles">
        <h6 class="dashhead-subtitle">USDA/NASS Statistics</h6>
        <h2 class="dashhead-title"><%= link_to @county.title, @county %></h2>
      </div>
    </div>
    <p>The
      <a href="https://www.agcensus.usda.gov">USDA Census of Agriculture</a>
      collects data every 5 years (e.g., 2017, 2012, 2007), while the
      <a href="https://www.nass.usda.gov">NASS Agricultural Survey</a>
      collects a smaller amount of data annually.</p>

    <ul class="nav nav-tabs" role="tablist">
      <% @years.each do |year|%>
        <li class="nav-item" role="presentation">
          <a href="#statistics-<%= year %>" class="nav-link <%= if year.to_i%5 == 2 then 'text-success' end %> <%= if year == @years.first then 'active' end %>" role="tab" data-toggle="tab" aria-controls="statistics-<%= year %>">
            <%= year %></a>
        </li>
      <% end %>
    </ul>

    <div class="tab-content mt-4">
      <% @years.each do |year|%>
        <div role="tabpanel" class="tab-pane<%= if year == @years.first then ' active' end %>" id="statistics-<%= year %>">
          <%= render partial: 'counties/nass_stats_by_year', locals: {year: year} %>
        </div>
      <% end %>
    </div>

    <h4 id='suppressed_values_explained'>(D)*: Suppressed/Censored Values</h4>

    <p>Based on USDA/NASS standards, these values were determined by NASS to be sensitive to a disclosure of information if they violated either of two criteria rules.
    </p>

    <p>1) The threshold rule was violated if the data cell contained less than three operations. For example, if only one farmer produced turkeys in a county, NASS could not publish the county total for turkey inventory without disclosing that
      individual’s information.
    </p>

    <p>
      <em>or</em>
    </p>

    <p>2) The dominance rule was violated if the distribution of the data within the cell allowed a data user to estimate any respondent’s data too closely. For example, if there are many farmers producing turkeys in a county and some of them were large
      enough to dominate the cell total, NASS could not publish the county total for turkey inventory without risking disclosing an individual respondent’s data.
    </p>

    <p>In both of these situations, the data were suppressed and a “(D)” was placed in the cell in the census publication table. These data cells were referred to as primary suppressions.</p>

    <p>Since most items were summed to marginal totals, primary suppressions within these summation relationships were protected by ensuring that there were additional suppressions within the linear relationship that provided adequate protection for the
      primary. A detailed computer routine selected additional data cells for suppression to ensure all primary suppressions were properly protected in all linear relationships in all tables. These data cells were referred to as complementary suppressions.
      These cells were not themselves sensitive to a disclosure of information but were suppressed to protect other primary suppressions. A “(D)” was also placed in the cell of the census publication table to indicate a complementary suppression. A data
      user could not determine whether a cell with a (D) represented a primary or a complementary suppression.</p>
  </div>
</div>

app/views/statistics/new.html.erb
<h1>New Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<div class="dashhead mt-4">
  <div class="dashhead-titles">
    <h6 class="dashhead-subtitle">USDA/NASS Statistics</h6>
    <h2 class="dashhead-title"><%= link_to @county.title, @county %></h2>
  </div>
</div>

<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Statistics", county_statistics_path(@county) %></li>
  <li class="breadcrumb-item active"><%= @statistic.short_desc %></li>
</ol>

<table class='table table-sm'>
  <tbody>
    <tr>
      <th>Description</th>
      <td><%= @statistic.short_desc.titleize %></td>
    </tr>
    <tr>
      <th>Year</th>
      <td><%= @statistic.year %></td>
    </tr>
    <tr>
      <th>Value</th>
      <td><%= @statistic.value %>
        <%= @statistic.unit_desc.titleize %></td>
    </tr>
    <tr>
      <th>County</th>
      <td><%= @statistic.county_name.titleize %></td>
    </tr>
    <tr>
      <th>State</th>
      <td><%= @statistic.state_name.titleize %></td>
    </tr>
    <tr>
      <th>Load Time</th>
      <td><%= @statistic.load_time %></td>
    </tr>
    <tr>
      <th>Commodity Description</th>
      <td><%= @statistic.commodity_desc.titleize %></td>
    </tr>
    <tr>
      <th>Domain Description</th>
      <td><%= @statistic.domain_desc.titleize %></td>
    </tr>
    <tr>
      <th>Statistic Category Description</th>
      <td><%= @statistic.statisticcat_desc.titleize %></td>
    </tr>
    <tr>
      <th>Frequency Description</th>
      <td><%= @statistic.freq_desc.titleize %></td>
    </tr>
    <tr>
      <th>Reference Period Description</th>
      <td><%= @statistic.reference_period_desc.titleize %></td>
    </tr>
    <tr>
      <th>Utilization Practice Description</th>
      <td><%= @statistic.util_practice_desc.titleize %></td>
    </tr>
    <tr>
      <th>Production Practice Description</th>
      <td><%= @statistic.prodn_practice_desc.titleize %></td>
    </tr>
    <tr>
      <th>Class Description</th>
      <td><%= @statistic.class_desc.titleize %></td>
    </tr>
    <tr>
      <th>Sector Description</th>
      <td><%= @statistic.sector_desc.titleize %></td>
    </tr>
    <tr>
      <th>Group Description</th>
      <td><%= @statistic.group_desc.titleize %></td>
    </tr>
    <tr>
      <th>Domain Category Description</th>
      <td><%= @statistic.domaincat_desc.titleize %></td>
    </tr>

    <% data_source =
      case @statistic.source_desc
      when 'SURVEY'
        link_to('NASS Survey Data', 'https://www.nass.usda.gov/')
      when 'CENSUS'
        link_to('USDA Ag Census', 'https://www.agcensus.usda.gov')
      end
    %>

      <tr>
        <th>Source</th>
        <td><%= data_source %>,
          <%= @statistic.year %></td>
      </tr>
      <tr>
        <th></th>
        <td></td>
      </tr>
    </tbody>
  </table>

  <%# debug @statistic %>