config/routes.rb
Rails.application.routes.draw do
  resources :steps
  resources :operations
  resources :crop_operations
  resources :livestock_operations
  resources :crop_inventories
  resources :livestock_inventories
  root to: 'counties#index'
  get '/counties/multiple', to: 'counties#show_multiple'
  resources :counties, only: [:index, :show] do
    resources :statistics, only: [:index]
  end
  resources :statistics, only: [:show]
  resources :energy_units, only: [:index]

  get '/crop_assumptions', to: 'application#crop_assumptions'
  get '/livestock_assumptions', to: 'application#livestock_assumptions'

  get '/links', to: 'application#links'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/counties_controller.rb
# frozen_string_literal: false

class CountiesController < ApplicationController
  before_action :set_county, only: [:show]
  before_action :set_custom_factors, only: [:show, :show_multiple]

  caches_page :index

  # GET /counties
  # GET /counties.json
  def index
    @counties = County.all
  end

  # GET /counties/1
  # GET /counties/1.json
  def show
    # used by partials to differentiate single county from multiple county
    @multiple = false

    ########### Initialize hashes ###########
    @acres = @county.acres_hash
    @head = @county.head_hash
    @classifications = @county.classifications_hash

    @crop_energy_dollars_hash = Hash.new(0)
    @crop_energy_dollars_per_acre_hash = Hash.new(0)
    @crop_co2e_emissions_hash = Hash.new(0)
    @crop_mmbtus_hash = Hash.new(0)
    @crop_field_dollars_hash = Hash.new(0)
    @crop_drying_dollars_hash = Hash.new(0)
    @crop_fertilizer_dollars_hash = Hash.new(0)

    @livestock_energy_dollars_hash = Hash.new(0)
    @livestock_energy_dollars_per_unit_hash = Hash.new(0)
    @livestock_co2e_emissions_hash = Hash.new(0)
    @livestock_mmbtus_hash = Hash.new(0)


    # used in calculating energy savings through electricity
    electricity = EnergyUnit.find_by(slug: 'electricity')


    CropOperation.order(:name).each do |op|
      # corn is special because it has a rotation factor as well; "corn silage", "forage", "oats", "soybeans" are not since they all use the same tillage factor
      @crop_energy_dollars_hash[op.name] += @acres[op.name].to_i * op.cached_energy_dollars_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)
      @crop_co2e_emissions_hash[op.name] += @acres[op.name].to_i * op.cached_co2e_emissions_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)
      @crop_mmbtus_hash[op.name] += @acres[op.name].to_i * op.cached_mmbtus_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)

      @crop_field_dollars_hash[op.name] += @acres[op.name].to_i * op.cached_field_dollars_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)
      @crop_drying_dollars_hash[op.name] += @acres[op.name].to_i * op.cached_drying_dollars_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)
      @crop_fertilizer_dollars_hash[op.name] += @acres[op.name].to_i * op.cached_fertilizer_dollars_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)

      if @energy_savings_factor > 0
        # subtract energy savings from energy_dollars, co2e, mmbtus, and drying hashes
        electricity_dollars_per_inventory_unit = op.cached_kwh_per_inventory_unit * electricity.dollars_per_unit
        electricity_co2e_per_inventory_unit = op.cached_kwh_per_inventory_unit * electricity.kg_of_co2e_emissions_per_unit
        electricity_mmbtu_per_inventory_unit = op.cached_kwh_per_inventory_unit * electricity.btu_per_unit * 0.00001

        @crop_energy_dollars_hash[op.name] -= @energy_savings_factor * @acres[op.name].to_i * electricity_dollars_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)
        @crop_co2e_emissions_hash[op.name] -= @energy_savings_factor * @acres[op.name].to_i * electricity_co2e_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)
        @crop_mmbtus_hash[op.name]         -= @energy_savings_factor * @acres[op.name].to_i * electricity_mmbtu_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)
        @crop_drying_dollars_hash[op.name] -= @energy_savings_factor * @acres[op.name].to_i * electricity_dollars_per_inventory_unit * @tillage_factor[op.tillage_practice] * (op.name == 'corn' ? @rotation_factor[op.rotation_practice] : 1)
        # @crop_fertilizer_dollars_hash and @crop_field_dollars_hash are unaffected because field and fertilizer operations use no electricity
      end
    end

    @acres.keys.each do |key|
      @crop_energy_dollars_per_acre_hash[key] = @crop_energy_dollars_hash[key] / @acres[key]
    end

    LivestockOperation.all.each do |op|
      # op.names => ["chickens", "hogs", "cattle"]
      # op.classifications => ["dairy cows", "other cattle", "broilers", "layers", nil, "beef cows"]
      # notice, hogs are the only livestock without a classification. The following methods work because op.name is used for the key only if op.classification is nil

      @livestock_energy_dollars_hash[op.name] += @classifications[(op.classification || op.name)].to_i * op.cached_energy_dollars_per_inventory_unit
      @livestock_co2e_emissions_hash[op.name] += @classifications[(op.classification || op.name)].to_i * op.cached_co2e_emissions_per_inventory_unit
      @livestock_mmbtus_hash[op.name] += @classifications[(op.classification || op.name)].to_i * op.cached_mmbtus_per_inventory_unit

      if @energy_savings_factor != 0
        # subtract energy savings from energy_dollars, co2e, and mmbtus hashes
        electricity_dollars_per_inventory_unit = op.cached_kwh_per_inventory_unit * electricity.dollars_per_unit
        electricity_co2e_per_inventory_unit = op.cached_kwh_per_inventory_unit * electricity.kg_of_co2e_emissions_per_unit
        electricity_mmbtu_per_inventory_unit = op.cached_kwh_per_inventory_unit * electricity.btu_per_unit * 0.00001

        @livestock_energy_dollars_hash[op.name] -= @energy_savings_factor * @classifications[(op.classification || op.name)].to_i * electricity_dollars_per_inventory_unit
        @livestock_co2e_emissions_hash[op.name] -= @energy_savings_factor * @classifications[(op.classification || op.name)].to_i * electricity_co2e_per_inventory_unit
        @livestock_mmbtus_hash[op.name]         -= @energy_savings_factor * @classifications[(op.classification || op.name)].to_i * electricity_mmbtu_per_inventory_unit
      end
    end

    # Build the @livestock_energy_dollars_per_unit_hash by taking the totals energy dollars divided by # of head
    @head.keys.each do |key|
      @livestock_energy_dollars_per_unit_hash[key] = @livestock_energy_dollars_hash[key] / @head[key]
    end

    #     ########### SUM THE VALUES IN THE HASHES FOR EASY VIEWS ###########

    @crop_energy_dollars = @crop_energy_dollars_hash.map(&:last).reduce(:+)
    @livestock_energy_dollars = @livestock_energy_dollars_hash.map(&:last).reduce(:+)
    @crop_field_dollars = @crop_field_dollars_hash.map(&:last).reduce(:+)
    @crop_drying_dollars = @crop_drying_dollars_hash.map(&:last).reduce(:+)
    @crop_fertilizer_dollars = @crop_fertilizer_dollars_hash.map(&:last).reduce(:+)

    #     ########### COMBINE CROP DATA WITH LIVESTOCK DATA ###########

    @combined_energy_dollars = @crop_energy_dollars + @livestock_energy_dollars
    @combined_co2e_emissions = @crop_co2e_emissions_hash.map(&:last).reduce(:+) + @livestock_co2e_emissions_hash.map(&:last).reduce(:+)
    @combined_mmbtus = @crop_mmbtus_hash.map(&:last).reduce(:+) + @livestock_mmbtus_hash.map(&:last).reduce(:+)

    ########

    respond_to do |format|
      format.html
      format.json
    end
  end

  def show_multiple
    if params[:selectedCounties].empty? || params[:selectedCounties].blank? || (params[:selectedCounties] == '[]')
      redirect_back(flash: { error: 'Please select at least one county.' }, fallback_location: root_path) # halts request cycle
    else
      @selected_counties = County.where(fips: JSON.parse(params[:selectedCounties])).order(:slug)
      # @selected_counties = County.all
      redirect_to @selected_counties.first if @selected_counties.size == 1

      # used by partials to differentiate single county from multiple county
      @multiple = true

      # Initialize Empty Hashes with zeros or other hashes with zeros
      @acres = Hash.new(0)
      @head = Hash.new(0)
      @classifications = Hash.new { |hash, key| hash[key] = Hash.new(0) }

      @crop_energy_dollars_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @crop_energy_dollars_per_acre_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @crop_co2e_emissions_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @crop_mmbtus_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @crop_field_dollars_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @crop_drying_dollars_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @crop_fertilizer_dollars_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }

      @aggregate_crop_energy_dollars = Hash.new(0)
      @aggregate_livestock_energy_dollars = Hash.new(0)
      @crop_field_dollars = Hash.new(0)
      @crop_drying_dollars = Hash.new(0)
      @crop_fertilizer_dollars = Hash.new(0)
      @combined_energy_dollars = Hash.new(0)
      @combined_mmbtus = Hash.new(0)
      @combined_co2e_emissions = Hash.new(0)

      @livestock_energy_dollars_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @livestock_energy_dollars_per_unit_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @livestock_co2e_emissions_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }
      @livestock_mmbtus_hash = Hash.new { |hash, key| hash[key] = Hash.new(0) }


      @crop_operations = CropOperation.order(:name)
      @livestock_operations = LivestockOperation.order(:name)

      # used in calculating energy savings through electricity
      electricity = EnergyUnit.find_by(slug: 'electricity')



      # Calculate values for each hash
      @selected_counties.each_with_index do |county, index|
        @acres[county.id] = county.acres_hash

app/helpers/counties_helper.rb
module CountiesHelper
  def latest_crop_stats_list(county)
    latest_stat_list(county, :crop)
  end

  def latest_livestock_stats_list(county)
    latest_stat_list(county, :livestock)
  end

  private

  def latest_stat_list(county, stat_type)
    string = '<ul class="list-unstyled">'

    case stat_type
    when :crop
      county.latest_crop_stats.each do |stat|
        string += "<li class='py-1'>#{link_to stat.short_desc.titleize, stat} <em>(#{stat.year})</em>: #{stat.value}</li>"
      end
    when :livestock
      county.latest_livestock_stats.each do |stat|
        string += "<li class='py-1'>#{link_to stat.short_desc.titleize, stat} <em>(#{stat.reference_period_desc.titleize}, #{stat.year})</em>: #{stat.value}</li>"
      end
    end
    string + '</ul>'
  end
end

app/views/counties/shared/_crop_production.html.erb
<h3 class='mt-5 mb-3' id='crop-production'>Crop Production ($<%= number_to_human( @multiple ? @crop_energy_dollars.values.sum : @crop_energy_dollars) %>)</h3>
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item" role="presentation">
    <a href="#crop-summary" class="nav-link active" role="tab" data-toggle="tab" aria-controls="crop-summary">Crop Summary</a>
  </li>
  <li class="nav-item" role="presentation">
    <a href="#crop-assumptions" class="nav-link" role="tab" data-toggle="tab" aria-controls="crop-assumptions">Assumptions</a>
  </li>
  <% unless @multiple %>
  <li class="nav-item" role="presentation">
    <a href="#land-use" class="nav-link" role="tab" data-toggle="tab" aria-controls="land-use">Land Area and Use</a>
  </li>
  <% end #unless @multiple %>
</ul>

<div class="tab-content mt-4">
  <div role="tabpanel" class="tab-pane active" id="crop-summary">
    <div class="row text-center m-t-md">
      <div class="col-md-4 mb-5">
        <div class="mx-auto">
          <%= column_chart((@multiple ? @combined_acres.sort : @acres.sort), colors: ["#40C0CB"], library: { yAxis: { min: 0, title: { text: 'Acres' } }, tooltip: { pointFormat: '<b>{point.y:,.0f}</b> acres', style: { textTransform: 'capitalize' } }, plotOptions: { series: { allowPointSelect:
          true } } }) %>
        </div>
        <h4>Acres Harvested</h4>
        <% unless @multiple %>
        <a
          tabindex="0"
          role="button"
          data-trigger="focus"
          class="btn btn-secondary"
          data-toggle="popover"
          data-placement="bottom"
          data-html="true"
          data-content='The <%= link_to "USDA Ag Census and NASS Survey data for #{ @county.title }", county_statistics_path(@county) %> provides numbers on how many acres of each crop is harvested annually.
          <br><%= latest_crop_stats_list(@county) %>
          '>
          <span class="icon icon-database"></span>
          About the Data</a>
          <% end #unless @multiple  %>
      </div>

      <div class="col-md-4 mb-4">
        <%= render 'dual_axis_column_chart', locals: {sector: 'crop' } %>
        <h4>Energy Cost by Crop</h4>
        <a
          tabindex="0"
          role="button"
          data-trigger="focus"
          class="btn btn-secondary"
          data-toggle="popover"
          data-placement="bottom"
          data-html="true"
          data-content='<h6>Energy Cost =</h6> Acres Harvested &times; <em>Energy Cost Per Acre</em><br><br>
          <ul class="list-unstyled">
            <% (@multiple ? @crop_energy_dollars_per_acre_hash.values.first : @crop_energy_dollars_per_acre_hash).each do |crop, dpa| # fixme: problem where first county doesn't have all crops raised%>
            <li class="py-1"><strong><%= crop.capitalize %>:</strong>&nbsp; <%= number_to_currency(dpa) %>/acre</li>
            <% end %>
          </ul>
          <em>Energy cost per acre for each cropping practice is equal to <%= link_to "the sum of fertilizer use, propane  and  electricity  use  for  drying,  diesel  in  field  operations  per acre", crop_assumptions_path %>, multipled by the <%= link_to "cost of each fuel or fertilizer", energy_units_path %>.
          '>
          <span class="icon icon-calculator"></span>
          About the Math</a>
      </div>
      <div class="col-md-4 mb-5">
        <div class="mx-auto">
          <%= pie_chart([["Drying", (@multiple ? @crop_drying_dollars.values.sum : @crop_drying_dollars)], ["Fertilizer", (@multiple ? @crop_fertilizer_dollars.values.sum : @crop_fertilizer_dollars)], ["Field Operations", (@multiple ? @crop_field_dollars.values.sum : @crop_field_dollars)] ], library: { tooltip: { pointFormat: '<b>${point.y:,.0f}</b><br/>' }, plotOptions: { series: { allowPointSelect:
          true }, pie: { dataLabels: { enabled: false }, showInLegend: true } } }) %>
        </div>
        <h4>Energy Cost by Category</h4>
        <a
          tabindex="0"
          role="button"
          data-trigger="focus"
          class="btn btn-secondary"
          data-toggle="popover"
          data-placement="bottom"
          data-html="true"
          data-content='<h6>Drying</h6><p>Annual drying cost is highly variable, but involves the cost of propane and electricity.</p> <h6>Fertilizer</h6><p>Fertilizer is the N, P, and K applied to each acre of a given crop/rotation practice. <%= link_to "View Cost Estimates", energy_units_path %></p><h6>Field Operations</h6><p>Field Operations include the diesel fuel required for each pass over an acre of field, given a particular crop, tillage practice, and crop rotation. <%= link_to "View data for each crop scenario here.", crop_assumptions_path %></p>'>
          <span class="icon icon-colours"></span>
          About the Categories</a>
      </div>
    </div>
    <!-- close row -->
  </div>
  <!-- close inner tabpanel -->

  <div role="tabpanel" class="tab-pane" id="crop-assumptions">
    <div class="row">
      <div class="col-lg-4 mb-5">
        <h5 class='mb-2'>Energy use per Acre</h5>
        <%= link_to "Field Operations, Fertilizer Use, and Drying Requirements per Acre", crop_assumptions_path %>
        <p>
          <strong>Data source:</strong>
          Iowa State University Extension</p>

        <h5 class='mb-2'>USDA/NASS Data</h5>
        <% if @multiple %>
        <%= "Statistics from #{ @selected_counties.count} counties" %>. <%= link_to "(e.g., #{ @selected_counties.first.title })", county_statistics_path(@selected_counties.first) %>
        <% else %>
        <%= link_to "All Statistics for #{ @county.title }", county_statistics_path(@county) %>
        <% end %>
        <p>
          <strong>Data source:</strong>
          USDA Ag Census, NASS Survey</p>

      </div>
      <div class="col-lg-4 mb-5">
        <h5 class='mb-2'>Tillage Assumptions</h5>
        <div class="list-group mb-3">
          <a class="list-group-item list-group-item-action justify-content-between" href="#">
            <span class="list-group-progress" style="width: <%= number_to_percentage(@tillage_factor['intensive_tillage']*100, precision: 0) %>;"></span>
            <span>Intensive Tillage</span>
            <span class="text-muted"><%= number_to_percentage(@tillage_factor['intensive_tillage']*100, precision: 0) %></span>
          </a>

          <a class="list-group-item list-group-item-action justify-content-between" href="#">
            <span class="list-group-progress" style="width: <%= number_to_percentage(@tillage_factor['reduced_tillage']*100, precision: 0) %>;"></span>
            <span>Reduced Tillage</span>
            <span class="text-muted"><%= number_to_percentage(@tillage_factor['reduced_tillage']*100, precision: 0) %></span>
          </a>

          <a class="list-group-item list-group-item-action justify-content-between" href="#">
            <span class="list-group-progress" style="width: <%= number_to_percentage(@tillage_factor['no_tillage']*100, precision: 0) %>;"></span>
            <span>No Till</span>
            <span class="text-muted"><%= number_to_percentage(@tillage_factor['no_tillage']*100, precision: 0) %></span>
          </a>
        </div>
        <!-- close list-group -->
        <p>
          <strong>Data source:</strong>
          Not available. Customize this value below.</p>
      </div>
      <!-- close col -->

      <div class="col-lg-4 mb-5">
        <h5 class='mb-2'>Rotation Assumptions</h5>
        <div class="list-group mb-3">
          <a class="list-group-item list-group-item-action justify-content-between" href="#">
            <span class="list-group-progress" style="width: <%= number_to_percentage(@rotation_factor ['following_corn']*100, precision: 0) %>;"></span>
            <span>Corn followed by Corn</span>
            <span class="text-muted"><%= number_to_percentage(@rotation_factor ['following_corn']*100, precision: 0) %></span>
          </a>

          <a class="list-group-item list-group-item-action justify-content-between" href="#">
            <span class="list-group-progress" style="width: <%= number_to_percentage(@rotation_factor ['following_soybeans']*100, precision: 0) %>;"></span>
            <span>Corn followed by Soybeans</span>
            <span class="text-muted"><%= number_to_percentage(@rotation_factor ['following_soybeans']*100, precision: 0) %></span>
          </a>
        </div>
        <!-- close list-group -->
        <p>
          <strong>Data source:</strong>
          Not available. Customize this value below.</p>
      </div>
      <!-- close col -->
    </div>
    <!-- close row -->
  </div>
  <!-- close inner tabpanel -->

  <% unless @multiple %>
  <div role="tabpanel" class="tab-pane" id="land-use">
    <div class="list-group mb-3">
      <h6 class="list-group-item list-group-item-action justify-content-between py-4">
        <span class="list-group-progress" style="width: 100%;"></span>
        <span>
          <strong>Total Land Area</strong>
        </span>
        <span class="text-muted">
          <strong><%= number_with_delimiter(@county.land_area_acres) %>
            acres</strong>
          (Ag Census:
          <%= @county.land_area_acres_year %>)</span>
      </h6>

      <a class="list-group-item list-group-item-action justify-content-between py-2" href="#">
        <span class="list-group-progress" style="width: <%= 100 * @county.agland_acres / @county.land_area_acres %>%;"></span>
        <span>- - -
          <strong>Ag Land</strong>
        </span>
        <span class="text-muted"><%= number_with_delimiter(@county.agland_acres) %>
          acres (Ag Census:
          <%= @county.cropland_acres_year %>)</span>
      </a>

      <a class="list-group-item list-group-item-action justify-content-between py-1" href="#">
        <span class="list-group-progress" style="width: <%= 100 * @county.cropland_acres / @county.land_area_acres %>%;"></span>
        <span>- - - - - - Cropland</span>
        <span class="text-muted"><%= number_with_delimiter(@county.cropland_acres) %>
          acres (Ag Census:
          <%= @county.cropland_acres_year %>)</span>
      </a>

      <a class="list-group-item list-group-item-action justify-content-between py-1" href="#">
        <span class="list-group-progress" style="width: <%= 100 * @county.cropland_harvested_acres / @county.land_area_acres %>%;"></span>
        <span>- - - - - - Cropland Harvested</span>
        <span class="text-muted"><%= number_with_delimiter(@county.cropland_harvested_acres) %>
          acres (Ag Census:
          <%= @county.cropland_acres_year %>)</span>
      </a>

      <%- @acres.sort_by{ |k, v| v.to_i }.reverse.to_h.each do |crop_name, crop_acres| -%>

        <a class="list-group-item list-group-item-action justify-content-between py-0" href="#">
          <span class="list-group-progress" style="width: <%= 100 * crop_acres.to_i / @county.land_area_acres %>%;"></span>
          <span>- - - - - - - - - - - -
            <em><%= crop_name.capitalize %></em>
          </span>
          <span class="text-muted"><%= number_with_delimiter(crop_acres) %>
            acres (NASS / Ag Census)</span>
        </a>

        <%- end -%>

          <a class="list-group-item list-group-item-action justify-content-between py-1" href="#">
            <span class="list-group-progress" style="width: <%= 100 * @county.pastureland_acres / @county.land_area_acres %>%;"></span>
            <span>- - - - - - Pastureland</span>
            <span class="text-muted"><%= number_with_delimiter(@county.pastureland_acres) %>
              acres (Ag Census:
              <%= @county.cropland_acres_year %>)</span>
          </a>

          <a class="list-group-item list-group-item-action justify-content-between py-1" href="#">
            <span class="list-group-progress" style="width: <%= 100 * @county.woodland_acres / @county.land_area_acres %>%;"></span>
            <span>- - - - - - Woodland</span>
            <span class="text-muted"><%= number_with_delimiter(@county.woodland_acres) %>
              acres (Ag Census:
              <%= @county.cropland_acres_year %>)</span>
          </a>

          <a class="list-group-item list-group-item-action justify-content-between py-1" href="#">
            <span class="list-group-progress" style="width: <%= 100 * @county.other_agland_acres / @county.land_area_acres %>%;"></span>
            <span>- - - - - - Other Ag Land</span>
            <span class="text-muted"><%= number_with_delimiter(@county.other_agland_acres) %>
              acres (Ag Census:
              <%= @county.cropland_acres_year %>)</span>
          </a>
        </div>
        <!-- close list-group -->
      </div>
      <!-- close inner tabpanel -->
      <% end %>
    </div>
    <!-- close inner tabcontent -->

app/views/counties/shared/_statcards.html.erb
<div class="hr-divider mt-2 mb-3">
  <h3 class="hr-divider-content hr-divider-heading">
    <%= @multiple ? "Multiple County Totals" : "Quick Stats" %>
  </h3>
</div>

<div class="row statcards">
  <div class="col-sm-8 mb-5 mb-md-3">
    <div class="statcard statcard-primary mb-3">
      <div class="p-3">
        <span class="statcard-desc">Annual Ag Production Energy Cost</span>
        <h2 class="statcard-number">
          $<%= number_to_human( @multiple ? @combined_energy_dollars.values.sum : @combined_energy_dollars ) %>
        </h2>
      </div>
    </div>
    <%= render 'combined_overview_pie_chart' %>
  </div>
  <div class="col-sm-4 mb-5 mb-md-3">
    <div class="statcard mb-3">
      <div class="p-3">
        <span class="statcard-desc">Annual Energy Use (MMBtu)</span>
        <h2 class="statcard-number">
          <%= number_to_human( @multiple ? @combined_mmbtus.values.sum : @combined_mmbtus ) %>
        </h2>
      </div>
    </div>
    <div class="statcard mb-3">
      <div class="p-3">
        <span class="statcard-desc">Annual CO<sub>2</sub>E Emissions from Energy (metric tons)</span>
        <h2 class="statcard-number">
          <%= display_emission_value( @multiple ? @combined_co2e_emissions.values.sum/1000 : @combined_co2e_emissions/1000 ) %>
        </h2>
      </div>
    </div>

    <div class="statcard mb-3">
      <div class="p-3">
        <span class="statcard-desc">Land Area (acres)</span>
        <h2 class="statcard-number">
          <%= number_with_delimiter(@multiple ? @selected_counties.sum(&:land_area_acres) : @county.land_area_acres) %>
        </h2>
      </div>
    </div>

    <div class="statcard mb-3">
      <div class="p-3">
        <span class="statcard-desc">Farm Operations (<%= @multiple ? @selected_counties.first.total_farm_operations_count_year : @county.total_farm_operations_count_year %>
          Ag Census)</span>
        <h2 class="statcard-number">
          <%= number_with_delimiter(@multiple ? @selected_counties.sum(&:total_farm_operations_count) : @county.total_farm_operations_count) %>
        </h2>
      </div>
    </div>
  </div>
</div>