config/routes.rb
Rails.application.routes.draw do
  resources :steps
  resources :operations
  resources :crop_operations
  resources :livestock_operations
  resources :crop_inventories
  resources :livestock_inventories
  root to: 'counties#index'
  get '/counties/multiple', to: 'counties#show_multiple'
  resources :counties, only: [:index, :show] do
    resources :statistics, only: [:index]
  end
  resources :statistics, only: [:show]
  resources :energy_units, only: [:index]

  get '/crop_assumptions', to: 'application#crop_assumptions'
  get '/livestock_assumptions', to: 'application#livestock_assumptions'

  get '/links', to: 'application#links'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :energy_unit
  has_and_belongs_to_many :operations

  scope :not_fertilizer, -> { where.not(category: 'fertilizer')}

  scope :survey, -> { where(source_desc: 'SURVEY') }


  after_save :update_operations

  # def self.distinct_category_names
  #   distinct.pluck(:category)
  # end

  def self.titleize_category(category_name)
    case category_name
    when nil
      'Livestock/Uncategorized'
    when 'field'
      'Field Operations'
    else
      category_name.titleize
    end
  end

  protected
    def update_operations
    end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
    @steps = Step.order(:sort_order).includes(:energy_unit)
  end

  private

  def step_params
    params.require(:step).permit(:type, :slug, :name, :cost, :energy_unit_id, :energy_units_used, :category, :subcategory, :source_text, :source_url, :notes)
  end
end

app/helpers/steps_helper.rb
module StepsHelper
  def source_content(step)
    if step.source_text.present?
      if step.source_url.present?
        link_to step.source_text, step.source_url, target: '_blank'
      else
        step.source_text
      end
    else
      '-'
    end
  end
end

app/views/steps/_form.html.erb
<%= form_for(step) do |f| %>
<% if step.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(step.errors.count, "error") %>
      prohibited this step from being saved:</h2>

    <ul>
      <% step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :type %>
  <%= f.text_field :type %>
</div>

<div class="field">
  <%= f.label :slug %>
  <%= f.text_field :slug %>
</div>

<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :cost %>
  <%= f.text_field :cost %>
</div>

<div class="field">
  <%= f.label :energy_unit_id %>
  <%= f.text_field :energy_unit_id %>
</div>

<div class="field">
  <%= f.label :energy_units_used %>
  <%= f.text_field :energy_units_used %>
</div>

<div class="field">
  <%= f.label :category %>
  <%= f.text_field :category %>
</div>

<div class="field">
  <%= f.label :subcategory %>
  <%= f.text_field :subcategory %>
</div>

<div class="field">
  <%= f.label :source_text %>
  <%= f.text_field :source_text %>
</div>

<div class="field">
  <%= f.label :source_url %>
  <%= f.text_field :source_url %>
</div>

<div class="field">
  <%= f.label :notes %>
  <%= f.text_field :notes %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing Step</h1>

<%= render 'form', step: @step %>

<%= link_to 'Show', @step %>
|
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Steps</h1>

<table class='table table-sm'>
  <thead>
    <tr>
      <th>Name</th>
      <!-- <th>Cost</th> -->
      <th>Energy</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>Source</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.name %></td>
        <!-- <td><%# step.cost %></td> -->
        <td><%= "#{step.energy_units_used} #{step.energy_unit.unit_short} #{step.energy_unit.name.downcase}" %></td>
        <td><%= step.category %></td>
        <td><%= step.subcategory %></td>
        <td><%= link_to step.source_text, step.source_url unless step.source_text.blank?%></td>
        <td><%= step.notes %></td>
        <td>
          <%# link_to 'Show', step %>
          </td>
          <td>
            <%# link_to 'Edit', edit_step_path(step) %>
            </td>
            <td>
              <%# link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New Step</h1>

<%= render 'form', step: @step %>

<%= link_to 'Back', steps_path %>