config/routes.rb
Rails.application.routes.draw do
  resources :steps
  resources :operations
  resources :crop_operations
  resources :livestock_operations
  resources :crop_inventories
  resources :livestock_inventories
  root to: 'counties#index'
  get '/counties/multiple', to: 'counties#show_multiple'
  resources :counties, only: [:index, :show] do
    resources :statistics, only: [:index]
  end
  resources :statistics, only: [:show]
  resources :energy_units, only: [:index]

  get '/crop_assumptions', to: 'application#crop_assumptions'
  get '/livestock_assumptions', to: 'application#livestock_assumptions'

  get '/links', to: 'application#links'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/operation.rb
class Operation < ApplicationRecord
  has_and_belongs_to_many :energy_units
  has_and_belongs_to_many :steps, -> { includes :energy_unit }
  has_and_belongs_to_many :livestock_steps
  has_and_belongs_to_many :crop_steps

  accepts_nested_attributes_for :steps, :livestock_steps, :crop_steps

  # Crop Operations
  scope :no_tillage, -> { where(tillage_practice: 'no_tillage') }
  scope :reduced_tillage, -> { where(tillage_practice: 'reduced_tillage') }
  scope :intensive_tillage, -> { where(tillage_practice: 'intensive_tillage') }

  scope :following_corn, -> { where(rotation_practice: 'following_corn') }
  scope :following_soybeans, -> { where(rotation_practice: 'following_soybeans') }

  scope :corn_grain, -> { where(name: 'corn') }
  scope :corn_silage, -> { where(name: 'corn silage') }
  scope :soybeans, -> { where(name: 'soybeans') }
  scope :forage, -> { where(name: 'forage') }
  scope :oats, -> { where(name: 'oats') }

  # similar to scopes, but for use at times when scopes can't be called.
  def self.with_tillage_practice(tillage_practice)
    where(tillage_practice: tillage_practice)
  end

  def self.with_rotation_practice(rotation_practice)
    where(rotation_practice: rotation_practice)
  end

  def kwh
    energy_units_per_inventory_unit_for(EnergyUnit.where(slug:'electricity'))
  end

  # Store the following values in the Operation table as shortcuts to speed up access to common values...
  # They are automatically updated in the database anytime the fuel prices are updated
  def update_cached_values
    energy_dollars = 0
    co2e = 0
    btu = BigDecimal(0)

    EnergyUnit.find_each do |energy_unit|
      energy_dollars += (energy_units_per_inventory_unit_for(energy_unit) * energy_unit.dollars_per_unit)
      co2e += (energy_units_per_inventory_unit_for(energy_unit) * energy_unit.kg_of_co2e_emissions_per_unit)
      btu += (energy_units_per_inventory_unit_for(energy_unit) * energy_unit.btu_per_unit)
    end

    update(cached_energy_dollars_per_inventory_unit: energy_dollars)
    update(cached_co2e_emissions_per_inventory_unit: co2e)
    update(cached_mmbtus_per_inventory_unit: btu * 0.00001)

    update(cached_kwh_per_inventory_unit: kwh)

    if type == 'CropOperation'
      field = 0
      fertilizer = 0
      drying = 0
      EnergyUnit.find_each do |energy_unit|
        field += (energy_units_per_inventory_unit_for_energy_unit_and_category(energy_unit, 'field') * energy_unit.dollars_per_unit)
        drying += (energy_units_per_inventory_unit_for_energy_unit_and_category(energy_unit, 'drying') * energy_unit.dollars_per_unit)
        fertilizer += (energy_units_per_inventory_unit_for_energy_unit_and_category(energy_unit, 'fertilizer') * energy_unit.dollars_per_unit)
      end
      update(cached_field_dollars_per_inventory_unit: field)
      update(cached_drying_dollars_per_inventory_unit: drying)
      update(cached_fertilizer_dollars_per_inventory_unit: fertilizer)
    end
  end

  def energy_units_per_inventory_unit_for(energy_unit)
    @energy_use ||= Hash.new do |h, key|
      h[key] = steps.where(energy_unit: key).sum(:energy_units_used).round(2)
    end
    @energy_use[energy_unit]
  end

  def energy_units_per_inventory_unit_for_energy_unit_and_category(energy_unit, category)
    # @energy_use ||= Hash.new do |h, key|
    steps.where(energy_unit: energy_unit, category: category).sum(:energy_units_used).round(2)
    # end
    # @energy_use[energy_unit]
  end

  def categories
    steps.pluck(:category).uniq
  end

  def subcategories
    steps.pluck(:subcategory).uniq
  end

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show]

  def index
    @operations = Operation.order(:name)
  end

  def show
    @steps = @operation.steps.order(:sort_order)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_operation
    @operation = Operation.find(params[:id])
  end

  def operation_params
    params.require(:operation).permit(:name, :rotation_practice, :tillage_practice, :description, :classification)
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
  def humanize(string)
    case string
    when 'reduced_tillage'
      'Reduced Tillage'
    when 'no_tillage'
      'No-till'
    when 'intensive_tillage'
      'Intensive Tillage'
    when 'following_corn'
      'Following corn'
    when 'following_soybeans'
      'Following soybeans'
    else
      string
    end
  end

  def description_plus_tillage_practice(operation)
    if operation.tillage_practice
      "#{operation.description} (#{humanize(operation.tillage_practice)})"
    else
      operation.description
    end
  end

end

app/views/operations/_form.html.erb
<%= form_for(operation.becomes(Operation)) do |f| %>
  <% if operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rotation_practice %>
    <%= f.text_field :rotation_practice %>
  </div>

  <div class="field">
    <%= f.label :tillage_practice %>
    <%= f.text_field :tillage_practice %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :classification %>
    <%= f.text_field :classification %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form', operation: @operation %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="dashhead mt-4">
  <div class="dashhead-titles">
    <h6 class="dashhead-subtitle">Documentation</h6>
    <h2 class="dashhead-title">Operations</h2>
  </div>
</div>

<table class='table table-bordered mb-0'>
  <thead class="thead-light">
    <tr>
      <th>Description</th>
      <% EnergyUnit.find_each do |e| %>
        <th><%= e.name %> / acre</th>
      <% end %>

    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= link_to description_plus_tillage_practice(operation), operation.becomes(Operation) %></td>
        <% EnergyUnit.find_each do |e| %>


          <td>
            <% if operation.energy_units_per_inventory_unit_for(e) != 0 %>
              <%= operation.energy_units_per_inventory_unit_for(e) %> <%= e.unit_short %>
            <% else %>
            <% end %>

          </td>
        <% end %>

        <td><%# link_to 'Edit', edit_operation_path(operation) %></td>
        <td><%# link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/operations/new.html.erb
<h1>New Operation</h1>

<%= render 'form', operation: @operation %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<ul>
<%- EnergyUnit.all.each do |u| -%>
  <li><%= u.name %>: <%= @operation.energy_units_per_inventory_unit_for(u) %> </li>
<% end %>
</ul>

<%= render partial: @operation %>